import { DevtoolsProvider } from '@providers/devtools';
import { GitHubBanner, Refine } from '@refinedev/core';
import { RefineKbar, RefineKbarProvider } from '@refinedev/kbar';
import { RefineSnackbarProvider, notificationProvider } from '@refinedev/mui';
import routerProvider from '@refinedev/nextjs-router';
import { Metadata } from 'next';
import { cookies } from 'next/headers';
import React, { Suspense } from 'react';

import { ColorModeContextProvider } from '@contexts/color-mode';
import { accessControlProvider } from '@providers/access-control-provider';
import { authProvider } from '@providers/auth-provider';
import { dataProvider } from '@providers/data-provider';

export const metadata: Metadata = {
    title: 'Refine',
    description: 'Generated by create refine app',
    icons: {
        icon: '/favicon.ico',
    },
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const cookieStore = cookies();
    const theme = cookieStore.get('theme');
    const defaultMode = theme?.value === 'dark' ? 'dark' : 'light';

    return (
        <html lang="en">
            <body>
                <Suspense>
                    <GitHubBanner />
                    <RefineKbarProvider>
                        <ColorModeContextProvider defaultMode={defaultMode}>
                            <RefineSnackbarProvider>
                                <DevtoolsProvider>
                                    <Refine
                                        routerProvider={routerProvider}
                                        dataProvider={dataProvider}
                                        notificationProvider={
                                            notificationProvider
                                        }
                                        authProvider={authProvider}
                                        accessControlProvider={
                                            accessControlProvider
                                        }
                                        resources={[
                                            {
                                                name: 'project',
                                                list: '/projects',
                                                create: '/projects/create',
                                                edit: '/projects/edit/:id',
                                                show: '/projects/show/:id',
                                                meta: {
                                                    canDelete: true,
                                                },
                                            },
                                        ]}
                                        options={{
                                            syncWithLocation: true,
                                            warnWhenUnsavedChanges: true,
                                            useNewQueryKeys: true,
                                            projectId: 'fEqQye-WWlKq9-8mmbEQ',
                                        }}
                                    >
                                        {children}
                                        <RefineKbar />
                                    </Refine>
                                </DevtoolsProvider>
                            </RefineSnackbarProvider>
                        </ColorModeContextProvider>
                    </RefineKbarProvider>
                </Suspense>
            </body>
        </html>
    );
}
